services:
  - type: web
    name: fashionhub-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SUPABASE_URL
        fromSecret: supabase_url
      - key: SUPABASE_KEY
        fromSecret: supabase_key
      - key: JWT_SECRET
        fromSecret: jwt_secret
